name: Nightly builds

on:
  push:
    branches:    
      - master

#  schedule:
#    - cron: '*/15 * * * *'

jobs:
 
  test_cron_a:
    name: Test scheduled build A
    runs-on: ubuntu-18.04
    env:
      DATE: ddd-$(date +%H%M)
    steps:
      - uses: actions/checkout@v1
      - run: |
          env
          mkdir foo
          date > foo/date.txt
          mv foo foo-a # "foo-a-$(date +%H%M)"
      - uses: actions/upload-artifact@master
        with:
          path: foo-a
          name: foo-a-${{ env.DATE }}

  test_cron_b:
    name: Test scheduled build B
    runs-on: ubuntu-18.04
    env:
      DATE: eee
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir foo
          date > foo/date.txt
          mv foo foo-b # "foo-b-$(date +%H%M)"
          echo ::set-env name=DATE::$(date +%H%M)
      - uses: actions/upload-artifact@master
        with:
          path: foo-b
          name: foo-b-${{ env.DATE }}
