name: Nightly builds

on:
  push:
    branches:    
      - master
  schedule:
    - cron: '*/15 * * * *'

jobs:
 
  test_cron_a:
    name: Test scheduled build A
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir foo
          date > foo/date.txt
          mv foo "foo-a-$(date +%H%M)"
      - uses: actions/upload-artifact@master
        env:
          DATE: test
        with:
          path: foo-*

  test_cron_b:
    name: Test scheduled build B
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir foo
          date > foo/date.txt
          mv foo "foo-b-$(date +%H%M)"
      - uses: actions/upload-artifact@master
        env:
          DATE: $(date +%H%M)
        with:
          path: foo-*
